#!/bin/bash

# Deletes all branches in current repo not in "origin".
# Credits: https://stackoverflow.com/a/33548037/1631514

git fetch -p
for branch in `git branch -vv | grep ': gone]' | awk '{print $1}'`; do
	git branch -D $branch;
done
