#!/bin/bash

# Push to origin only the current branch
# Additional flags (e.g. "--force") can be appended at invokation.

ORIGIN_NAME=$(git config --local "branch.$(git symbolic-ref --short HEAD).remote")
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

CMD="git push ${ORIGIN_NAME} ${BRANCH_NAME} $@"
echo "Running: $CMD"
$CMD
